### ISSUE TITLE
AllocateAnyPages shouldn't be used?

### ISSUE THREAD

**Issue by eeropomell** [ajxs/uefi-elf-bootloader#3]
When you allocate memory for the segments, you use AllocateAnyPages, which means it will ignore the value of segment_virtual_address and will instead pick the pages randomly.

I dont know if this was on purpose but a couple lines above you printed "Allocating memory at address x".

"Allocation requests of Type AllocateAnyPages allocate any available range of pages that satisfies the
request. On input, the address pointed to by Memory is ignored. "

https://github.com/ajxs/uefi-elf-bootloader/blob/e97031817cb2411cac46b5594320b2ee15266d76/src/bootloader/src/loader.c#L61

**Comment by ajxs** [comment]
My apologies for the late response. I'll update my Github preferences so I get notified of issues by email.
Thank you so much for looking into this! I'm really glad you noticed this.
I think there's a bigger problem with my implementation. The address passed to `AllocatePages`seems to be the  _physical_ page address. This is a mistake in my code. It just happens to work with the example kernel because it's not particularly concerned with where it's allocated. You're right that in this case the code should allocate memory at the specified address, however the virtual memory mapping still needs to be performed. This needs a few extra changes. I'll have a look into this and update this issue.

**Comment by ajxs** [comment]
Thank you so much for pointing this issue out. I really appreciate your help.
It turns out there were some other issues with how I was allocating the kernel pages. I merged your PR in so that you got contributor credit, and then pushed some other changes that fix the incorrect implementation. The kernel is now loaded into memory at the correct physical address.
The other issue you raised about the kernel's physical address will need to be addressed as well. UEFI doesn't give any guarantees about what physical memory will be free at boot time, so I'll need to make some changes to the example kernel to resolve this.
